#!/usr/bin/perl -w
# PPath
# Surya Saha    04/23/2010 10:38:34 AM  
# reading reports generated by LipoP (http://www.cbs.dtu.dk/services/LipoP/) for LAS proteins  
# and writing a Excel file for predicted Lipoprotein signal peptides
# write a gff file for Gbrowse 


unless (@ARGV == 2){
	print "USAGE: $0 <LipoP txt output> <GFF>\n";
	exit;
}

use strict;
use warnings;

my ($rec,@preds,%gff,%gffvals,$i,$j,$k,$l,$ctr,@temp,@temp1,$spictr,$spiictr,$tmhctr);

unless(open(OUTXLS,">$ARGV[0].xls")){print "not able to open $ARGV[0].xls\n\n";exit;}
unless(open(OUTGFF,">$ARGV[0].gff")){print "not able to open $ARGV[0].gff\n\n";exit;}
unless(open(LPREP,$ARGV[0])){print "not able to open $ARGV[0]\n\n";exit;}
chomp $ARGV[1];
unless(open(INGFF,$ARGV[1])){print "not able to open $ARGV[1]\n\n";exit;}

## LipoP  predictions
#gi_254780139_ref_YP_003064552.1_ CYT score=-0.200913
#gi_254780140_ref_YP_003064553.1_ TMH score=8.06339 margin=8.264303
#gi_254780141_ref_YP_003064554.1_ SpII score=13.4768 margin=6.84287 cleavage=28-29 Pos+2=F
#gi_254780142_ref_YP_003064555.1_ CYT score=-0.200913
#gi_254780143_ref_YP_003064556.1_ CYT score=-0.200913
#gi_254780170_ref_YP_003064583.1_ SpI score=9.25687 margin=9.457783 cleavage=24-25
$spictr=$spiictr=$tmhctr=$ctr=0;
while ($rec=<LPREP>){
	if ($rec=~ /^\#/){next;}
	@temp = split(' ',$rec);
	#only record non CYT predictions
	if ($temp[1] ne 'CYT'){
		@temp1 = split('_',$temp[0]);
		$preds[$ctr][0]=$temp1[1];#GI
		$preds[$ctr][1]=$temp[1];#class
		if ($temp[1] eq 'SpI'){# regular signal peptide
			$spictr++;
			for (2..4){	$preds[$ctr][$_]=$temp[$_];}
		}
		elsif ($temp[1] eq 'SpII'){# lipoprotein signal peptide
			$spiictr++;
			for (2..5){ $preds[$ctr][$_]=$temp[$_];}
		}
		elsif ($temp[1] eq 'TMH'){#n-term transmembrane helix
			$tmhctr++;
			$preds[$ctr][2]=$temp[2];#score
			$preds[$ctr][3]=$temp[3];#margin
		}
		$ctr++;
	}
	@temp=(); @temp1=();
}
close(LPREP);

# Reading in the GFF file
#NC_012985.2	RefSeq	gene	36	407	.	+	.	locus_tag=CLIBASIA_00005;db_xref=GeneID:8210255
#NC_012985.2	RefSeq	CDS	36	404	.	+	0	locus_tag=CLIBASIA_00005;transl_table=11;product=hypothetical protein;protein_id=YP_003064535.1;db_xref=GI:254780122;db_xref=GeneID:8210255;exon_number=1
#NC_012985.2	RefSeq	start_codon	36	38	.	+	0	locus_tag=CLIBASIA_00005;transl_table=11;product=hypothetical protein;protein_id=YP_003064535.1;db_xref=GI:254780122;db_xref=GeneID:8210255;exon_number=1
#NC_012985.2	RefSeq	stop_codon	405	407	.	+	0	locus_tag=CLIBASIA_00005;transl_table=11;product=hypothetical protein;protein_id=YP_003064535.1;db_xref=GI:254780122;db_xref=GeneID:8210255;exon_number=1
#NC_012985.2	RefSeq	gene	497	820	.	+	.	locus_tag=CLIBASIA_00010;db_xref=GeneID:8209098
#NC_012985.2	RefSeq	CDS	497	817	.	+	0	locus_tag=CLIBASIA_00010;transl_table=11;product=hypothetical protein;protein_id=YP_003064536.1;db_xref=GI:254780123;db_xref=GeneID:8209098;exon_number=1
$ctr=0;
while ($rec=<INGFF>){
	if ($rec=~ /^\#/){next;}
	@temp = split("\t",$rec);
	chomp $temp[8];
	if ($temp[2] eq 'CDS'){
		@temp1=split(';',$temp[8]);
		# the attributes are not same for all CDS
		foreach $i (@temp1){
			$j=[split('=',$i)];
			if (@$j[0] ne 'db_xref'){
				$gffvals{@$j[0]}=@$j[1];	
			}
			else{
				# spl case since 2 db_xref values..WHY?????
				# db_xref=GI:254780122;db_xref=GeneID:8210255;
				if (@$j[1]=~ /^GI/){
					$gffvals{@$j[0]}=@$j[1];
				}
				else{
					@$j[1]=~ s/^GeneID://;
					$gffvals{'GeneID'}=@$j[1];# using a diff key here
				}
			}
		}
		# fix GI value and use it as key
		$gffvals{'db_xref'}=~ s/^GI://;
		$gff{$gffvals{'db_xref'}}=[@temp];
		%gffvals=();
	}
	@temp=();
}
close(INGFF);

# Printing the XLS file
print OUTXLS "Sig peps\tLipoprotein sig peps\tn-terminal tran. helix\n";
print OUTXLS "$spictr\t$spiictr\t$tmhctr\n\n\n";

print OUTXLS "Product\tLocus tag\tAcc\tSpI\tSpII\tTMH\n";
foreach $i (@preds){
	if(!(exists $gff{$i->[0]})){ print STDERR "No GFF entry found on @$i\n"; exit;}# if the protein does not exist in GFF file
	$j=$gff{$i->[0]};
	@temp=split(';',@$j[8]);
	# split key=value pairs and store in hash
	foreach $l (@temp){
		@temp1=split('=',$l);
		$gffvals{$temp1[0]}=$temp1[1];
	}
	# fix acc num
	$gffvals{'protein_id'}=~ s/.1$//;
	print OUTXLS "$gffvals{'product'}\t$gffvals{'locus_tag'}\t$gffvals{'protein_id'}\t";

	if ($i->[1] eq 'SpI') {print OUTXLS "Y\tN\tN\n";}
	elsif ($i->[1] eq 'SpII') {
		print OUTXLS "N\tY\tN\n";
		#print out lipoprotein predictions coordinates in GFF file for gbrowse
		print OUTGFF "NC_012985.2\tLipoP\tmat_peptide\t";
		my ($mpstr,$mpend,$site);
		$site=$i->[4];
		$site=~ s/^cleavage\=//;
		$site=~ s/\-\d+$//;
		#if + strand
		if (@$j[6] eq '+'){
			$mpend=@$j[4];
			$mpstr=@$j[3]+($site*3)-1;
			print OUTGFF "$mpstr\t$mpend\t.\t+\t.\tName=$gffvals{'locus_tag'}\(LipoP\)\;Note=lipoprotein\;\n";
		}
		# if - strand
		elsif (@$j[6] eq '-'){
			$mpstr=@$j[3];
			$mpend=@$j[4]-($site*3)+1;
			print OUTGFF "$mpstr\t$mpend\t.\t-\t.\tName=$gffvals{'locus_tag'}\(LipoP\)\;Note=lipoprotein\;\n";
		}		
	}
	elsif ($i->[1] eq 'TMH') {print OUTXLS "N\tN\tY\n";}
	@temp=();
	%gffvals=();
}
close(OUTGFF);
close(OUTXLS);
